apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
  name: dev
- cluster:
  name: uat
- cluster:
  name: prod

users:
- name: sa-edit
- name: sa-view

contexts:
- context:
  name: dev
- context:
  name: uat
- context:
  name: prod